spring.application.name=sb-crud-mysql-app

spring.datasource.url=jdbc:mysql://localhost:3306/userdb?useSSL=false
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update